# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-ssm-parameters
  description: "This component is responsible for provisioning Parameter Store resources against AWS SSM"
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component








